include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # 类型安全
    always_declare_return_types: true
    avoid_dynamic_calls: true
    avoid_type_to_string: true
    
    # 代码风格
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true
    require_trailing_commas: true
    
    # 代码组织
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    
    # 避免错误
    avoid_print: true
    avoid_slow_async_io: true
    cancel_subscriptions: true
    close_sinks: true
    
    # 不必要的代码
    unnecessary_this: true
    unnecessary_late: true
    unnecessary_null_checks: true
    
    # 文档
    public_member_api_docs: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    missing_required_param: error
    missing_return: error
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

